// The command list is the plugin's whole surface (docs/prompts/native-push-plan.md
// §5.1). tauri-plugin generates one allow/deny permission per entry into
// permissions/autogenerated/, and permissions/default.toml grants them.
// `register_listener` and `remove_listener` are the Plugin base class's own
// commands: `addPluginListener` in the page calls them, so the `token`,
// `opened` and `received` events need them allowed.
const COMMANDS: &[&str] = &[
  "status",
  "register",
  "unregister",
  "take_open",
  "clear",
  "set_badge",
  "open_settings",
  // docs/prompts/notification-names-plan.md §4: the label map a push is
  // named from. Android only for now; iOS answers it once N-ios exists.
  "set_labels",
  "register_listener",
  "remove_listener",
];

fn main() {
  tauri_plugin::Builder::new(COMMANDS)
    .ios_path("ios")
    .android_path("android")
    .build();
}
